### PR TITLE
Fix #251: dbal driver - safe queue creation

### LINKED ISSUE #251: DBAL-based queue constantly raises SQL-level errors
As per https://github.com/bernardphp/bernard/blob/3b781583fd73deb2f612847c58dfa94e3eb5672e/src/Driver/DoctrineDriver.php#L40-L45, bernard tries to constantly bash the DB with `INSERT` statements that will fail.

While this seems to be acceptable at first, some database engines mark transactions with failed SQL statements as "failed transactions", rendering the entire DB connection unusable.

Few things to be done here

 * wrap the entire statement in a transaction (safest way)
 * use `INSERT IGNORE` (not always supported, therefore not going there)
 * do a `SELECT` and then an `INSERT` (relatively low-risk, since queues don't get destroyed/recreated often)

I'll provide a patch for this today, if this seems reasonable.

### PR DESCRIPTION
**Pull request by Ocramius**
Since we don't have `UPSERT` support in DBAL (and sadly will not be in it for a while), this PR fixes #251 by providing graceful handling of queue creation.
1. operations are executed in a transaction
2. only unique constraint exceptions are caught (very important! if the DB dies, that's not something we can ignore)
3. avoid causing duplicate key issues, when possible

### CODE REVIEW

File: tests/Bernard/Tests/Driver/DoctrineDriverTest.php [hunk 1]
```diff
@@ -39,6 +51,64 @@ public function testCreateAndRemoveQueue()
...
+            ->disableOriginalConstructor()
+            ->getMock();
+
+        $connection->expects(self::once())->method('transactional')->willReturnCallback('call_user_func');
+        $connection->expects(self::once())->method('insert')->willThrowException($exception);
+        $connection->expects(self::any())->method('createQueryBuilder')->willReturn($queryBuilder);
+
+        $driver = new DoctrineDriver($connection);
+
+        $driver->createQueue('foo');
```
Comment (Ocramius) [inline tests/Bernard/Tests/Driver/DoctrineDriverTest.php]: Note: no assertions provided here. The assertion is `self::once()` on the `insert` call.

**Comment by henrikbjorn** [comment]
any idea why the tests are failing?

**Comment by Ocramius** [comment]
Falures are at install/pecl/pyrus. Not stuff that I touched :-\

**Comment by danydev** [comment]
@henrikbjorn what can I do to speed up the merge of this one? As explained on #275 this prevents Bernard to work on PostgreSQL 9.5.x

**Comment by henrikbjorn** [comment]
Im currently sick so ill look at it, when my head clears up.

**Comment by henrikbjorn** [comment]
@Ocramius Thanks for this, sorry for me being so slow getting back and merging this.

**Comment by Ocramius** [comment]
Dude, I have PRs that are pending since 5 years, and you are not paid to do
this: no need to be sorry!

Thanks for merging!

**Comment by danydev** [comment]
@henrikbjorn thank you!

**Comment by ruudk** [comment]
Thanks! You guys are awesome  :D

**Comment by danydev** [comment]
@henrikbjorn sorry to ask again, but I'm wondering if you intentionally merged it on 0.x branch, or you meant to merge it on master. If the merge on 0.x is intentional, what's the process to have it merged back on master?

**Comment by henrikbjorn** [comment]
@danydev you are a life saver, didn't even notice. I have merged it into the master branch as well.

**Comment by danydev** [comment]
@henrikbjorn ahah you're welcome but I don't see it on [master](https://github.com/bernardphp/bernard/blob/master/src/Driver/DoctrineDriver.php) yet

**Comment by danydev** [comment]
@henrikbjorn ping :-)

**Comment by asprega** [comment]
Hi @henrikbjorn ! We could really use this fix on master, even better if in a new tagged release. Are you able to merge this to master or are there any issues?
